feat: axios 설정 추가
team-christmas/todowith-fe pull request #13
Opened 2022-01-09 11:05 UTC by yerin-dev

- axios 설정 추가
- apis 폴더 목업 파일 추가
- console eslint 경고 해제
[노션](https://www.notion.so/axios-30a06ab2dc8449dcb5e57c99484930d6)

2022-01-10 16:52 UTC, MaetDol commented on src/apis/index.js
> +export {common, auth, user};
```javascript
export * as common from './common';
```
의 형태로 바꾸면 추가하거나 제거하기에 용이하지 않을까 싶어요
어떻게 생각하시나요?

2022-01-10 16:52 UTC, MaetDol commented on src/utils/fetchJson.js
> +  DELETE: "delete",
`PATCH` 도 추가 부탁드려요!

2022-01-10 16:52 UTC, MaetDol commented on src/utils/fetchJson.js
> +  }
에러 상황을 좀 더 명확하게 표현하면 좋을 것 같아요!
```javascript
console.error(`Error occurred while sending request to ${url}, error: ${e}`);
```
또한 `console.log`는 `undefined`를 리턴하기 때문에 `return` 문을 생략해도 되지않을까 싶어요

2022-01-10 16:52 UTC, MaetDol commented on src/utils/fetchJson.js
> +const request = async (method, url, data = {}) => {
혹시 모든 함수를 `화살표 함수`로 만든다거나 `function`으로 선언한다거나 규칙이 정해진게 있을까요?

2022-01-10 16:54 UTC, MaetDol requested changes
확인 부탁드려요!

2022-01-10 17:35 UTC, sukyoungshin commented on src/apis/index.js
> +export {common, auth, user};
동일한 의견 드립니다.

2022-01-10 17:35 UTC, sukyoungshin commented on src/utils/fetchJson.js
> +  }
동일한 의견 드립니다.

2022-01-10 17:35 UTC, sukyoungshin commented on src/utils/fetchJson.js
> +  DELETE: "delete",
동일한 의견 드립니다.

2022-01-10 17:37 UTC, sukyoungshin reviewed
확인 부탁드립니다. 
브랜치명 camelCase 규칙 리마인더 드립니다.

2022-01-10 23:09 UTC, yerin-agreable commented on src/utils/fetchJson.js
> +const request = async (method, url, data = {}) => {
해당 규칙은 일감으로 만들어 작업 하면 될 것 으로 보입니다.

2022-01-10 23:23 UTC, yerin-dev commented on src/apis/index.js
> +export {common, auth, user};
이 형태가 가능한 형태인가요?

2022-01-11 03:58 UTC, MaetDol commented on src/apis/index.js
> +export {common, auth, user};
넵~! [MDN 예문](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax) 아래쪽을 확인해주시면 될 것 같아요!

2022-01-11 03:59 UTC, MaetDol commented on src/utils/fetchJson.js
> +const request = async (method, url, data = {}) => {
아하 따로 정해진게 있는데 놓쳤었나 싶어 여쭤봤어요!
강제는 아니군요 알겠습니다~

2022-01-11 04:16 UTC, yerin-agreable commented on src/apis/index.js
> +export {common, auth, user};
해당 내용이 eslint 때문에 계속 오류나서 말씀드린 것인데, 관련해서 해당 브랜치에 커밋을 날려주실 수 있으신가요?

2022-01-11 04:51 UTC, MaetDol commented on src/apis/index.js
> +export {common, auth, user};
넵! 커밋 푸시 완료했습니다
제쪽에선 따로 경고나 에러가 안나오네요

2022-01-11 12:34 UTC, yerin-dev commented on src/apis/index.js
> +export {common, auth, user};
![image](https://user-images.githubusercontent.com/40863185/148943320-e6640085-6143-453b-94e2-2a8ca3f89e32.png)
 해당 내용에 에러가 있습니다 @MaetDol

2022-01-11 12:35 UTC, MaetDol commented on src/apis/index.js
> +export {common, auth, user};
에러메시지를 보여주실 수 있으신가요? 
제쪽에서 `import` 테스트까지 문제없이 진행했어서 어떤 에러인지 모르겠어요

2022-01-11 13:26 UTC, yerin-dev commented on src/apis/index.js
> +export {common, auth, user};
![image](https://user-images.githubusercontent.com/40863185/148950712-8a6d4cfd-c733-4b04-ba3f-fb7942656c0c.png)

동작은 저도 잘 됩니다.. 이런 에러가 뜨네요

2022-01-11 13:31 UTC, yerin-dev commented on src/apis/index.js
> +export {common, auth, user};
https://r4bb1t.tistory.com/68
이글을 보고 추가 커밋으로 바벨 파서를 붙였습니다.. ^_ㅠ 최신 문법 관련이슈네요 새 커밋 확인 부탁드려요

2022-01-11 15:15 UTC, MaetDol approved these changes

2022-01-12 11:19 UTC, sukyoungshin reviewed
코멘트 확인 부탁드립니다.

2022-01-12 11:19 UTC, sukyoungshin commented on src/apis/index.js
> +export * as user from './user';
force push로 인해 이전 내역 확인이 불가능합니다. 또한 불필요한 코드리뷰가 늘어납니다. 
force push 자제 부탁드립니다.

2022-01-12 11:21 UTC, sukyoungshin approved these changes
👍

2022-01-13 09:23 UTC, merged