style: airbnb-eslint에 맞게 기본스타일 변경
team-christmas/todowith-fe pull request #6
Opened 2021-12-01 16:53 UTC by sukyoungshin

[노션](https://www.notion.so/airbnb-eslint-ce5e47f90b804d4d8cf3f627ea003cc0)
- airbnb eslint configuration 버그로 인해 .eslintrc.js에 코드 추가 (line21 - 26)
- *참고 https://stackoverflow.com/questions/69928061/struggling-with-typescript-react-eslint-and-simple-arrow-functions-components

2021-12-01 16:54 UTC, MaetDol approved these changes
룩굿투미!

2021-12-02 00:57 UTC, yerin-agreable requested changes

2021-12-02 00:57 UTC, yerin-agreable commented on src/App.jsx
> +  return <>ㅋ</>;
ㅋ 는 간지의 표현인가요 ?

2021-12-02 00:59 UTC, yerin-dev requested changes

2021-12-02 00:59 UTC, yerin-dev commented on src/App.jsx
> +  return <>ㅋ</>;
ㅋ는 간지용인가여?!

2021-12-02 09:03 UTC, MaetDol commented on src/App.jsx
> +  return <>ㅋ</>;
<></>로 비워두니까 린트에러가 나더라구요 ㅋㅋㅋㅋㅋ

2021-12-02 22:17 UTC, sukyoungshin commented on src/App.jsx
> +  return <>ㅋ</>;
린트에러땜시 뭐라고 써야할 것 같아서 집어넣은 ㅋ 입니다...

2021-12-05 13:35 UTC, yerin-dev approved these changes
LGTM!

2021-12-05 19:31 UTC, merged