feat : 라우터 설정 (v6)
team-christmas/todowith-fe pull request #9
Opened 2022-01-06 14:13 UTC by sukyoungshin

- react-router (v6) 기본설정 ( [노션](https://www.notion.so/react-router-v6-da875bd4ced94c4e9e6f03c4250b7a72) )

2022-01-08 06:30 UTC, MaetDol requested changes

2022-01-08 06:30 UTC, MaetDol commented on src/router.js
> +        <Route path="/" element={<Layout />}>
혹시 `path="/"` 에서 `"/"` 를 상수화 해주실 수 있으신가요?
추후에 추가될 URL들과 통일하려면 미리 상수로 분리해두는게 좋을 것 같아서 의견드려요!

2022-01-08 06:31 UTC, MaetDol approved these changes

2022-01-08 06:34 UTC, MaetDol requested changes
실수로 Approve를 눌러버려서 다시 요청남겨요!

2022-01-09 10:34 UTC, yerin-dev requested changes

2022-01-09 10:34 UTC, yerin-dev commented on src/pages/IndexPage.js
> +  return (
eslint 활성화 된 상태일까요? 리턴만 있는 경우 단축 리턴이 들어가지 않아 리뷰 드립니다

2022-01-09 10:34 UTC, yerin-dev commented on src/router.js
> +        <Route path="/" element={<Layout />}>
동일한 의견 드립니다.

2022-01-10 17:16 UTC, sukyoungshin commented on src/pages/IndexPage.js
> +  return (
아직 변경되지 않은 eslint 룰이 있어서, 바로 변경하기 어렵습니다.
#12 해당PR이 머지되면 변경하도록 하겠습니다.  @yerin-dev

2022-01-10 17:21 UTC, sukyoungshin commented on src/router.js
> +        <Route path="/" element={<Layout />}>
#11 해당 PR 머지되면 작업하겠습니다. @yerin-dev @MaetDol

2022-01-10 23:14 UTC, yerin-dev commented on src/pages/IndexPage.js
> +  return (
리뷰 내용은 () => 화살표 함수를 말한것이 아니긴 한데.. 방금 머지하여서 변경 부탁드려요~

2022-01-11 19:17 UTC, sukyoungshin commented on src/pages/IndexPage.js
> +  return (
넵 변경하겠습니다

2022-01-12 11:16 UTC, MaetDol approved these changes

2022-01-12 11:16 UTC, sukyoungshin commented
코드리뷰 반영 및 react-router 설치하였습니다. 
코드 재 리뷰 부탁드립니다. ea6a54b

@yerin-dev @MaetDol

2022-01-13 09:23 UTC, yerin-dev requested changes

2022-01-13 09:23 UTC, yerin-dev commented on src/router.js
> +        <Route path={URL.ROOT} element={<Layout />}>
페이지가 많아질 때를 대비하여 정의파일을 바깥으로 빼서 map 돌리면 좋을 것 같습니다

2022-01-13 15:51 UTC, sukyoungshin commented on src/router.js
> +        <Route path={URL.ROOT} element={<Layout />}>
React Router 6는 기존 버전과 달리,배열 형태로 Route property를 전달할 수 없으며, `useRoutes`라는 훅을 이용하여 객체 형태로 넘겨야 한다고 합니다. 해당 내용 [StackOverFlow](https://stackoverflow.com/questions/40541994/multiple-path-names-for-a-same-component-in-react-router)링크 참조하오니 확인부탁드리오며, 공식문서에 따라 작업 진행하도록 하겠습니다. @yerin-dev

2022-01-14 08:56 UTC, yerin-dev commented on src/router.js
> +        <Route path={URL.ROOT} element={<Layout />}>
useRoutes로 진행하심이 좋을것 같네요

2022-01-14 16:42 UTC, sukyoungshin commented on src/router.js
> +        <Route path={URL.ROOT} element={<Layout />}>
코멘트 확인 하였습니다. 말씀해주신대로 `useRoutes`를 사용하여 진행하겠습니다.

2022-01-18 17:15 UTC, sukyoungshin commented on src/router.js
> +        <Route path={URL.ROOT} element={<Layout />}>
수정사항 확인 부탁드립니다.  f4db31ab243b8ce750b7ea25c248db536c16afaf
@yerin-dev @MaetDol

2022-06-23 09:11 UTC, closed without merging